### ISSUE TITLE
Models Folder

### ISSUE THREAD

**Issue by ondoheer** [josephmancuso/masonite#47]
I find the way you are following the Laravel patterns so clearly, but having worked with laravel on many projects, I find we always end up modifying things. For example, on large projects, we always end up creating an ```  http/models ``` folder to order them as we require, would you find it purposeful to modify this basic behaviour?

**Comment by josephmancuso** [comment]
I did always think it was a weird placement of models. I'm going to look into this more because although I haven't moved models since I only really ever had < 10 which didn't clutter up the project too much but I always like the idea that the import was `app.User` instead of maybe `app.models.User`. 

I'm going to strongly consider this and well as research Laravels decision to do so and see if it makes sense. I'll ask right now is Laravels slack channel

**Comment by josephmancuso** [comment]
I'm going to put them in the next release. 

@ondoheer would you like to work on this issues? it really just involves moving the User model into a models folder and changing the references inside "3.2 - API Routing" docs and also inside `config/auth.py` and `routes/api.py`

**Comment by josephmancuso** [comment]
I don't recommend putting this inside app/http as it doesn't have anything to do with routes or requests like controllers do. Obviously the user can move it to wherever they like but I think it's a good base framework conventions to separate http and models

**Comment by josephmancuso** [comment]
I think this is a good reasoning for this: https://github.com/laravel/laravel/pull/3821#issuecomment-228740120

I think a way to do something like `craft model Models/User` will be good. I opened up a new issue for this

**Comment by josephmancuso** [comment]
https://github.com/josephmancuso/masonite/issues/52

**Comment by josephmancuso** [comment]
Completed
