### ISSUE TITLE
Modular design?

### ISSUE THREAD

**Issue by ondoheer** [josephmancuso/masonite#48]
One of the thigs we struggle most on large Laravel projects and was really easy to solve in Flask was the project structure. I know there are ways to acomplish this in Laravel, but it's unnatural and when Laravel updates it just might not work.

Maybe giving the users the felxibility to work like [this](https://nicolaswidart.com/blog/writing-modular-applications-with-laravel-modules) or having a ```create module``` craft command?

**Comment by josephmancuso** [comment]
Ok I like this idea. Maybe even make a separate package out of this using Masonite Package which I'll document today. How should we specify it in the route? Maybe something like `route('url', 'Controller@method').module('Product')`? Which will look into Product.http.controllers instead of app.http.controllers?

**Comment by josephmancuso** [comment]
After thinking about this I think this should be a separate installable package all together but apart of the Official Package ecosystem. 

masonite-cli actually comes with a `craft` and `craft-vendor` command. I'll write up some documentation on this since theres no current documented way to create commands but it looks something like:

    $ craft-vendor package
    $ craft-vendor package submodule
    $ craft-vendor package submodule function

what this does is allows you to `pip install package` and then allows that module to be able to tap into the craft command line. We could actually even create something like a `craft vendor` command to condense everything into the normal `craft` namespace. That might be more fluent.

The whole workflow could look something like

    $ pip install masonite-module
    $ craft vendor masonite-module create Products

Which can scaffold out the products like normal.

I'll add documentation today on how to setup a package to tap into the command line

**Comment by josephmancuso** [comment]
I think this is a good idea but I'm going to hold off on this and implement it after we have several key features established like Middleware and the file structure

**Comment by ondoheer** [comment]
I just reviewd the whole discussion. Defdinetly should hold up, but your proposal sounds good. They way it's handeled in Flask is that eacbh package is a middleware, and Flask-bootstrap for example, just defines a new set of templates if you decide to extend from them.

**Comment by josephmancuso** [comment]
Will close this to open it back up at a later time
