### ISSUE TITLE
unpythonic code

### ISSUE THREAD

**Issue by xcombelle** [josephmancuso/masonite#61]
The first example of the code documentation looks hugly because unpythonic

Instead of
````python

ROUTES = [ Get().route('/checkout', CheckoutController().show), 

Post().route('/checkout', CheckoutController().store), ]

````

I would love to see

````python

ROUTES = [ route('/checkout',
get=show,
post=store, ),
]
#see also import this, zen of python
````

**Comment by josephmancuso** [comment]
Interesting, where is the controller though in your example? You reference show and store

**Comment by josephmancuso** [comment]
This probably doesn't sound great and I'll get flak but I'm not really going to accept issues with "un pythonic code". I understand the benefits of being "pythonic" but I think it's pretty vague. If pythonic means making it look better and easier to understand AND memorable and looks nice I'll accept it but I won't accept any change in syntax because it's simply "not the python way to do it". With that being said I'm open to any issues but being "un pythonic" rubs me the wrong way. The route system is inspired by Laravel but any changes that would be better and supports controllers in the same way I'm open for suggestions

**Comment by josephmancuso** [comment]
I'm also keeping string controllers in, I like the idea of not having to import every controller as there's not really a need to do so in a file which will have a lot of routes and therefore imports

**Comment by xcombelle** [comment]
I totally agree that pythonicity is a vague and weakly defined.

However, it is one of the greatest trait of python just after its community.

**Comment by josephmancuso** [comment]
right. I'm a big fan of it too but i'd rather have easy to remember and readable syntax over "be more pythonic"

**Comment by xcombelle** [comment]
Looks that your easy to remember is just easy to remember for some php/lavarel base user.

I don't want enlarge the thread anymore, but definitely php and easy to use is in my opinion such an oxymoron that I had already launched a language war

**Comment by josephmancuso** [comment]
Yeah that's true. Easy to remember and readable is pretty subjective but I've used both PHP and python significantly and I enjoy using setters rather than using parameters. I understand that this is completely my opinion though and you might rather use parameters than setters.
